services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: ashusingh007/chat-in-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI = mongodb://mongo:27017/chatin
    depends_on:
      - mongo
    networks:
      - app-network



volumes:
  mongo-db:
  
networks:
  app-network: